#!/bin/sh

while [ "$(pwd | grep .git)" != "" ]
do
	cd ..
done

if [ -z $(command -v php) ]
then
	echo 'php not found'
	exit 1
fi

if [ ! -f artisan ]
then
	echo 'artisan not found'
    exit 1
fi

php artisan down

if [ "$(git diff --name-only HEAD HEAD~1 | grep composer)" != "" ]
then
	composer install -o --no-dev --no-interaction
fi

php artisan optimize
php artisan up
