#!/bin/sh


#BRANCH="main" 

# Put absolute php path to use 
PHP=php

# Put composer command to use if use different composer than default
COMPOSER=$(which composer)

DIFF=""
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ -z "$BRANCH" ]
    then
        DIFF="$DIFF `git diff --name-only $oldrev $newrev`"
    else
        if [ "$BRANCH" == "$branch" ]
        then
            DIFF="$DIFF `git diff --name-only $oldrev $newrev`"
        fi
    fi
done

if [ "$(git submodule)" != "" ]
then
	git submodule update --remote --init
fi

cd $GIT_DIR/..

if [ -z $(command -v $PHP) ]
then
	echo 'php not found'
	exit 1
fi

if [ ! -f artisan ]
then
	echo 'artisan not found'
    exit 1
fi


$PHP artisan down


if [ "$(echo $DIFF | grep composer)" != "" ]
then
	$PHP $COMPOSER install -o --no-dev --no-interaction
fi

if [ "$(echo $DIFF | grep migration)" != "" ]
then
	$PHP artisan migrate --force
fi

$PHP artisan optimize
$PHP artisan up
