#!/bin/sh


#BRANCH="main" 


DIFF=""
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ -z "$BRANCH" ]
    then
        DIFF="$DIFF `git diff --name-only $oldrev $newrev`"
    else
        if [ "$BRANCH" == "$branch" ]
        then
            DIFF="$DIFF `git diff --name-only $oldrev $newrev`"
        fi
    fi
done


while [ "$(pwd | grep .git)" != "" ]
do
	cd ..
done


if [ -z $(command -v php) ]
then
	echo 'php not found'
	exit 1
fi

if [ ! -f artisan ]
then
	echo 'artisan not found'
    exit 1
fi


php artisan down


if [ "$(echo $DIFF | grep composer)" != "" ]
then
	composer install -o --no-dev --no-interaction
fi

if [ "$(echo $DIFF | grep migration)" != "" ]
then
	php artisan migrate --force
fi

php artisan optimize
php artisan up
