#!/bin/sh

mix=$(git diff --name-only --cached | grep -e "^.*.js$" -e "^resources")
if [[ -n "$mix" ]]
then
	yarn production
	git add public/mix-manifest.json
	git add public/css/*
	git add public/js/*
fi
